version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file: .env
    expose:
      - '3001'
    working_dir: '/usr/src/app'
    environment:
      DB_HOST: 'db'
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:9.5
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "db-data:/var/lib/postgresql/data"
      restart: on-failure
volumes:
  db-data:
